/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

const fileMap = {
  
  "clients.baml": "client<llm> MindBridgeModel {\n  provider openai-generic\n  options {\n    base_url \"https://api.openai.com/v1\"\n    model \"gpt-5-mini\"\n  }\n}\n\nretry_policy GenerationRetry {\n  max_retries 2\n  strategy {\n    type exponential_backoff\n    delay_ms 300\n    multiplier 1.5\n    max_delay_ms 3000\n  }\n}\n",
  "content-generation.baml": "class SourceChunk {\n  id string\n  text string\n}\n\nenum ExerciseDifficulty {\n  EASY\n  STANDARD\n}\n\nenum SourceChunkId {\n  @@dynamic\n}\n\nclass LearningObjective {\n  text string\n  source_chunk_ids SourceChunkId[]\n}\n\nclass QuizQuestion {\n  question string\n  options string[]\n  correct_answer string\n  explanation string\n  source_chunk_ids SourceChunkId[]\n}\n\nclass Exercise {\n  difficulty ExerciseDifficulty\n  prompt string\n  expected_answer string\n  explanation string\n  source_chunk_ids SourceChunkId[]\n}\n\nclass LessonDraft {\n  title string\n  summary string\n  summary_source_chunk_ids SourceChunkId[]\n  objectives LearningObjective[]\n  quiz_questions QuizQuestion[]\n  exercises Exercise[]\n}\n\nfunction GenerateLessonDraft(source_chunks: SourceChunk[]) -> LessonDraft {\n  client MindBridgeModel\n  prompt #\"\n    Bạn là chuyên gia thiết kế học liệu. Chỉ sử dụng thông tin trong các đoạn tài liệu nguồn dưới đây để tạo học liệu tiếng Việt.\n\n    Yêu cầu:\n    - Tạo tiêu đề và tóm tắt bài học rõ ràng, phù hợp với nội dung nguồn.\n    - Tạo các mục tiêu học tập có thể quan sát/đánh giá.\n    - Tạo ít nhất 10 câu quiz. Mỗi câu có các lựa chọn, một đáp án đúng và lời giải thích.\n    - Tạo đúng một bài tập EASY và ít nhất một bài tập STANDARD.\n    - Với mọi claim, mục tiêu, câu quiz và bài tập, chỉ liệt kê ID của các source chunk thực sự hỗ trợ nội dung đó.\n    - Không tạo dữ kiện, ví dụ hoặc nguồn không có trong tài liệu. Nếu tài liệu thiếu thông tin, hãy diễn đạt thận trọng.\n    - Chỉ trích những nguồn quan trọng thôi nếu có quá nhiều > 10 nguồn.\n\n    ĐOẠN TÀI LIỆU NGUỒN:\n    {{ source_chunks }}\n\n    {{ ctx.output_format }}\n  \"#\n}\n",
  "generators.baml": "// This helps use auto generate libraries you can use in the language of\n// your choice. You can have multiple generators if you use multiple languages.\n// Just ensure that the output_dir is different for each generator.\ngenerator target {\n    // Valid values: \"python/pydantic\", \"typescript\", \"go\", \"rust\", \"ruby/sorbet\", \"rest/openapi\"\n    output_type \"typescript\"\n\n    // Where the generated code will be saved (relative to baml_src/)\n    output_dir \"../\"\n\n    // The version of the BAML package you have installed (e.g. same version as your baml-py or @boundaryml/baml).\n    // The BAML VSCode extension version should also match this version.\n    version \"0.223.0\"\n\n    // Valid values: \"sync\", \"async\"\n    // This controls what `b.FunctionName()` will be (sync or async).\n    default_client_mode async\n}\n",
}
export const getBamlFiles = () => {
    return fileMap;
}