/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  Exercise,  ExerciseDifficulty,  LearningObjective,  LessonDraft,  QuizQuestion,  SourceChunk } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface Exercise {
      difficulty?: types.ExerciseDifficulty | null
      prompt?: string | null
      expected_answer?: string | null
      explanation?: string | null
      source_chunk_ids: string[]
    }
    export interface LearningObjective {
      text?: string | null
      source_chunk_ids: string[]
    }
    export interface LessonDraft {
      title?: string | null
      summary?: string | null
      summary_source_chunk_ids: string[]
      objectives: LearningObjective[]
      quiz_questions: QuizQuestion[]
      exercises: Exercise[]
    }
    export interface QuizQuestion {
      question?: string | null
      options: string[]
      correct_answer?: string | null
      explanation?: string | null
      source_chunk_ids: string[]
    }
    export interface SourceChunk {
      id?: string | null
      text?: string | null
    }
}